easypage_list:
    path:  /
    defaults: { _controller: mtt_easypage.page_controller:listAction }

easypage_show:
    path:  /{slug}
    defaults: { _controller: mtt_easypage.page_controller:showAction }