easypage_index:
    path:  /
    controller: Mtt\EasyPageBundle\Controller\PageController::listAction

easypage_show:
    path:  /{slug}
    controller: Mtt\EasyPageBundle\Controller\PageController::showAction