services:
   mtt_easypage.page.service:
        class: Mtt\EasyPageBundle\Service\PageService
        arguments:
               - '@doctrine.orm.entity_manager'
               - '%mtt_easy_page.page_entity%'
               - '@router.default'

   mtt_easypage.doctrine.page_listener:
        class: Mtt\EasyPageBundle\Listeners\Doctrine\PageListener
        arguments:
            - '@cocur_slugify'
        tags:
            - { name: doctrine.orm.entity_listener }